#include "symmetry.h"
#include <cstring>
#include <vector>
#include <cassert>

// ---------------------------------------------------------------------------
// The 48-element symmetry group is generated by 4 basic symmetries.
// Each is expressed as a SymElem (cube-group element, position-indexed):
//   cp/ep: where the cubie whose home is position p ends up
//   co:    corner orientation contribution (mod 3)
//   cm:    orientation multiplier — 1 if the symmetry preserves the U/D/L/R/F/B
//          orientation classes' cyclic order, 2 if it reverses it
//   ef:    edge flip contribution (XOR)
//
// cm is derived from how the symmetry permutes the three axis classes
// {U/D}, {R/L}, {F/B}: an even permutation of the cyclic order gives cm=1,
// an odd permutation gives cm=2.
// ---------------------------------------------------------------------------
namespace {

SymElem make_identity() {
    SymElem s;
    for (int c = 0; c < N_CORNERS; ++c) { s.cp[c] = static_cast<uint8_t>(c); s.co[c] = 0; }
    s.cm = 1;
    for (int e = 0; e < N_EDGES; ++e) { s.ep[e] = static_cast<uint8_t>(e); s.ef[e] = 0; }
    return s;
}

// ---- Generator 1: S_U4 — 90° CW whole-cube turn about the U-D axis --------
// Face map: F→R, R→B, B→L, L→F. The U/D stickers stay on the U/D faces, so the
// corner-orientation reference is preserved → cm = 1, co = 0.
SymElem gen_U4() {
    SymElem s;
    uint8_t cp[] = {3,0,1,2, 7,4,5,6};
    std::memcpy(s.cp, cp, 8);
    for (int c = 0; c < 8; ++c) s.co[c] = 0;
    s.cm = 1;
    uint8_t ep[] = {3,0,1,2, 7,4,5,6, 11,8,9,10};
    std::memcpy(s.ep, ep, 12);
    uint8_t ef[] = {0,0,0,0, 0,0,0,0, 1,1,1,1};
    std::memcpy(s.ef, ef, 12);
    return s;
}

// ---- Generator 2: S_F2 — 180° whole-cube turn about the F-B axis ----------
// Face map: U↔D, L↔R, F/B fixed. Two class-swaps (even) → cm = 1.
SymElem gen_F2() {
    SymElem s;
    uint8_t cp[] = {5,4,7,6, 1,0,3,2};
    std::memcpy(s.cp, cp, 8);
    for (int c = 0; c < 8; ++c) s.co[c] = 0;
    s.cm = 1;
    uint8_t ep[] = {6,5,4,7, 2,1,0,3, 9,8,11,10};
    std::memcpy(s.ep, ep, 12);
    for (int e = 0; e < 12; ++e) s.ef[e] = 0;
    return s;
}

// ---- Generator 3: S_URF3 — 120° turn about the URF-DBL body diagonal ------
// Face map: U→R→F→U, D→L→B→D. Cyclic rotation of the 3 axis classes (even)
// → cm = 1, but introduces a uniform twist of +1.
SymElem gen_URF3() {
    SymElem s;
    uint8_t cp[] = {0,3,7,4, 1,2,6,5};
    std::memcpy(s.cp, cp, 8);
    for (int c = 0; c < 8; ++c) s.co[c] = 1;
    s.cm = 1;
    uint8_t ep[] = {8,0,11,4, 9,2,10,6, 1,3,7,5};
    std::memcpy(s.ep, ep, 12);
    uint8_t ef[] = {1,1,1,1, 1,1,1,1, 0,0,0,0};
    std::memcpy(s.ef, ef, 12);
    return s;
}

// ---- Generator 4: S_LR2 — left-right mirror reflection (L↔R) --------------
// Face map: L↔R, U/D/F/B fixed. A mirror reverses the sense of "clockwise",
// so corner twist o → -o ≡ 2o (mod 3) → cm = 2, co = 0.
SymElem gen_LR2() {
    SymElem s;
    uint8_t cp[] = {1,0,3,2, 5,4,7,6};
    std::memcpy(s.cp, cp, 8);
    for (int c = 0; c < 8; ++c) s.co[c] = 0;
    s.cm = 2;
    uint8_t ep[] = {2,1,0,3, 6,5,4,7, 9,8,11,10};
    std::memcpy(s.ep, ep, 12);
    for (int e = 0; e < 12; ++e) s.ef[e] = 0;
    return s;
}

bool elem_equal(const SymElem& a, const SymElem& b) {
    return std::memcmp(a.cp, b.cp, 8)  == 0
        && std::memcmp(a.co, b.co, 8)  == 0
        && a.cm == b.cm
        && std::memcmp(a.ep, b.ep, 12) == 0
        && std::memcmp(a.ef, b.ef, 12) == 0;
}

SymElem invert(const SymElem& x) {
    SymElem r;
    r.cm = x.cm; // 1->1, 2->2 (self-inverse mod 3)
    for (int p = 0; p < N_CORNERS; ++p) {
        r.cp[x.cp[p]] = static_cast<uint8_t>(p);
        // compose(x, r) corner ori at p must be 0:
        //   (r.cm * x.co[p] + r.co[x.cp[p]]) % 3 == 0
        r.co[x.cp[p]] = static_cast<uint8_t>((3u - (r.cm * x.co[p]) % 3u) % 3u);
    }
    for (int p = 0; p < N_EDGES; ++p) {
        r.ep[x.ep[p]] = static_cast<uint8_t>(p);
        r.ef[x.ep[p]] = x.ef[p];
    }
    return r;
}

} // namespace

SymmetryTables::SymmetryTables() {
    // 3 generators of the 16-element U/D-axis-preserving symmetry subgroup.
    // gen_URF3() is intentionally excluded (needs position-dependent twist).
    const SymElem generators[3] = { gen_U4(), gen_F2(), gen_LR2() };

    std::vector<SymElem> elems;
    elems.reserve(N_SYM);
    elems.push_back(make_identity());

    for (std::size_t i = 0; i < elems.size(); ++i) {
        for (const SymElem& g : generators) {
            SymElem next = sym_compose(elems[i], g);
            bool found = false;
            for (const SymElem& e : elems)
                if (elem_equal(next, e)) { found = true; break; }
            if (!found) elems.push_back(next);
        }
    }

    assert(elems.size() == static_cast<std::size_t>(N_SYM) &&
           "Symmetry group generation produced wrong count");

    for (int i = 0; i < N_SYM; ++i) {
        sym[i] = elems[i];
        inv[i] = invert(elems[i]);
    }
}

const SymmetryTables& SymmetryTables::get() {
    static const SymmetryTables instance;
    return instance;
}
